http:
  middlewares:
    tailscale-only:
      ipAllowList:
        sourceRange:
          - "100.64.0.0/10"
          - "fd7a:115c:a1e0::/48"
          - "127.0.0.1/32"
          - "172.16.0.0/12"
          - "10.0.0.0/8"
          - "192.168.0.0/16"
        ipStrategy:
          depth: 0
